#!/bin/bash
set -euxo pipefail

# Reinstall the server extension explicitly from source
pip install --force-reinstall jupyter-vscode-proxy==0.6.0

# Enable the server extension
jupyter server extension enable --py jupyter_vscode_proxy

# List to confirm it was registered
jupyter server extension list

