#!/bin/bash
set -euxo pipefail

# 1. Reinstall and enable the Jupyter proxy extensions
pip install --force-reinstall jupyter-server-proxy jupyter-vscode-proxy==0.6.0
jupyter server extension enable --py jupyter_vscode_proxy
jupyter server extension list
